// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgzDn085dY2IuL2fXx5hg9d9aYPjc5B40',
    appId: '1:30164116362:web:fccba02529f3e0f80b5e73',
    messagingSenderId: '30164116362',
    projectId: 'ispapp-9f09d',
    authDomain: 'ispapp-9f09d.firebaseapp.com',
    storageBucket: 'ispapp-9f09d.firebasestorage.app',
    measurementId: 'G-HNQRHLZC3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxmXyQzc3PpvDTt6QYDkesZnzZFQG-m3s',
    appId: '1:30164116362:android:5e71a176eb33c8ca0b5e73',
    messagingSenderId: '30164116362',
    projectId: 'ispapp-9f09d',
    storageBucket: 'ispapp-9f09d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaKjIJODOw-PDqQaPvvLEfS9qc5vfVHr8',
    appId: '1:30164116362:ios:9ed8779544abf7b10b5e73',
    messagingSenderId: '30164116362',
    projectId: 'ispapp-9f09d',
    storageBucket: 'ispapp-9f09d.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaKjIJODOw-PDqQaPvvLEfS9qc5vfVHr8',
    appId: '1:30164116362:ios:9ed8779544abf7b10b5e73',
    messagingSenderId: '30164116362',
    projectId: 'ispapp-9f09d',
    storageBucket: 'ispapp-9f09d.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgzDn085dY2IuL2fXx5hg9d9aYPjc5B40',
    appId: '1:30164116362:web:0c1e57f913763c390b5e73',
    messagingSenderId: '30164116362',
    projectId: 'ispapp-9f09d',
    authDomain: 'ispapp-9f09d.firebaseapp.com',
    storageBucket: 'ispapp-9f09d.firebasestorage.app',
    measurementId: 'G-H2KD6ND15W',
  );
}
